# Site settings
title: Neeraj Mehra
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Neeraj Mehra
user_description: I'm a Software Engineer, always searching for the challenges.
user_title: A Quality Engineer
email: mehraneeraj.17@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
