# Site settings
title: Neeraj Mehra
description: Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Neeraj Mehra
user_description: I'm a Software Engineer, always searching for the challenges.
user_title: Quality Engineer
email: mehraneeraj.17@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]

color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

  # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/mehraneerajilum
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  - title: instagram
    url: https://www.instagram.com/mehraneerajilum
  - title: github
    url: https://www.github.com/mehraneeraj17
  - title: linkedin
    url: https://www.linkedin.com/in/neeraj-mehra-b9510341

  # Footer settings
footer:
  copyright: Neeraj Mehra
  location: Location

  # Postal address (add as many lines as necessary)
address:
  - line: Electronic City
  - line: Bangalore, KA 560100

  # Build settings
markdown: kramdown
permalink: pretty
